version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  setup:
    machine: true
    resource_class: class/custom  # Ensure your self-hosted runner is used here
    steps:
      - checkout  # Checkout the code from the repository
      - run:
          name: Generate config
          command: |
            tools/circle-generate-config.sh generated_config.yml
      - continuation/continue:
          configuration_path: /var/lib/circleci-runner/workdir/generated_config.yml
jobs:
  build_and_test:
    machine: true
    resource_class: class/custom  # Use your self-hosted runner for this job too
    steps:
      - run:
          name: Prepare cache key
          command: tools/make-certs-cache-key.sh > certs_cache_key && cat certs_cache_key
      - restore_cache:
          name: Restore certificates
          key: certs-cache-{{ checksum "certs_cache_key" }}
      - run:
          name: Build certificates if not cached
          command: test -f tools/ssl/mongooseim/key.pem || make certs
      - run:
          name: Print cert hashes for debugging
          command: find tools/ssl -type f -exec md5sum {} \; | sort
      
      - save_cache:
          name: Cache built certs
          key: certs-cache-{{ checksum "certs_cache_key" }}
          paths:
            - ~/project/tools/ssl/ca
            - ~/project/tools/ssl/ca-clients
            - ~/project/tools/ssl/mongooseim

workflows:
  setup_workflow:
    jobs:
      - setup
      - build_and_test:
          requires:
            - setup
