version: 2.1

references:
  - &OTP25 mongooseim/cimg-erlang:25.3.2.9
  - &OTP26 mongooseim/cimg-erlang:26.2.2
  - &ENTRYPOINT ["/bin/sh", "-c", "eval ${INSTALL_DEPS_CMD:-echo} && echo __INJECT_FILES__ | eval ${BASE32DEC:-base32 --decode} | bash"]
  - &CERT_KEY certs-cache-{{ checksum "certs_cache_key" }}-v3
  - &DEPS_CACHE_KEY deps-cache-{{ checksum "rebar.lock" }}-{{ checksum "big_tests/rebar.lock" }}-{{ checksum "otp_version" }}-v5
  - &BUILD_CACHE_KEY build-cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "otp_version" }}-v6

# Define the self-hosted runner's resource class 
executors:
  otp_25:
    machine: true
    resource_class: class/custom
  otp_26:
    machine: true
    resource_class: class/custom

commands:
  fetch_build_packages:
    steps:
      - run:
          name: Install packages necessary for building
          command: |
            tools/circle-install-packages.sh \
            'libssl-dev unixodbc-dev unixodbc tdsodbc rsync zlib1g-dev'

  maybe_build_deps_and_cache:
    steps:
      - restore_cache:
          name: Maybe restore all rebar3 dependencies
          key: *DEPS_CACHE_KEY
      - run:
          name: Get and compile deps
          command: |
            tools/configure with-all
            tools/build-deps.sh
      - run:
          name: Get and compile big_tests deps
          command: |
            tools/build-test-deps.sh
      - save_cache:
          name: Cache built dependencies
          key: *DEPS_CACHE_KEY
          paths:
            - ~/project/_build/default/
            - ~/project/big_tests/_build/default/

  prepare_for_cache:
    steps:
      - run:
          name: Prepare for cache
          command: bash -c 'echo $OTP_VERSION-$ARCH > otp_version'

  cache_prod_build:
    parameters:
      arch:
        type: string
    steps:
      - run:
          name: Create prod tarball
          command: |
            export BUILD_PATH=_build/prod/rel/mongooseim
            tar czh --transform="s,${BUILD_PATH},mongooseim,S" \
              -f mongooseim-<<parameters.arch>>.tar.gz ${BUILD_PATH}
      - save_cache:
          key: *BUILD_CACHE_KEY
          paths: ~/project/mongooseim-<<parameters.arch>>.tar.gz

  restore_prod_build:
    parameters:
      arch:
        type: string
    steps:
      - run:
          echo $OTP_VERSION-<<parameters.arch>> > otp_version
      - restore_cache:
          key: *BUILD_CACHE_KEY

  run_coverage_analysis:
    steps:
      - run:
          name: Coverage
          when: on_success
          command: |
            echo "Success!"
            ./rebar3 codecov analyze
            tools/circle-upload-codecov.sh

  run_small_tests:
    steps:
      - run:
          name: Wait for redis
          command: |
            tools/wait-for-it.sh -p 6379
      - run:
          name: Run Small Tests
          command: |
            tools/test.sh -p small_tests -s true -e true

jobs:
  build_in_docker:
    executor: otp_25
    parallelism: 1
    environment:
      SKIP_RELEASE: 1
      SKIP_COV: 0
      SKIP_CERT_BUILD: 1
    steps:
      - checkout
      - prepare_for_cache
      - fetch_build_packages
      - maybe_build_deps_and_cache
      - run: ./rebar3 compile
      - run:
          name: Generate development releases
          command: ./tools/build-releases.sh
      - run:
          name: Build Big Tests
          command: tools/build-tests.sh
      - persist_workspace

  small_tests_in_docker:
    executor: otp_25_redis
    steps:
      - run_small_tests
      - run_coverage_analysis

filters: &all_tags
  tags:
    only: /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_in_docker:
          filters: *all_tags
      - small_tests_in_docker:
          filters: *all_tags
